version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db_fg:
    image: postgres:13
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: ./.env

  backend:
    image: danildogg/foodgram_backend
    restart: always
    env_file: ./.env
    depends_on:
      - db_fg
    volumes:
      - static:/app/static/
      - media:/app/media/

  frontend:
    image: danildogg/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - 9000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/media/
    env_file: .env
    depends_on:
      - frontend
